### PR TITLE
feat: Low-level API 3.2.0 upgrade

### LINKED ISSUE #27: Low-level API 3.2.0 upgrade

### PR DESCRIPTION
**Pull request by MarekSuchanek**
- Template metamodel in tests is updated to 4
- Template ID in tests is made valid (only `.` as special character should be allowed in organization ID)
- Cassettes that are being updated in #26 were skipped
- Cassettes that require connection to Registry (pulls) were also skipped - Does it require to configure Registry manually?

closes #27

### CODE REVIEW

**Review by drahoja9 — CHANGES_REQUESTED** [review]
Seems good to me. 

Regarding tests that require Registry, there are 2 problems:
* Test `test_pull_templates` uses `registry_template_id` fixture, which defines template version from the Registry – change the version to `'dsw:science-europe:1.5.0'` (or any other metamodel 4 template) and it should work just fine.
* Test `test_update_templates` rely on the fact that there are at least two distinct versions of a single template of given metamodel version (currently metamodel version 4). This is quite brittle and easy to break, so I propose a change to this test in dc6b397077902408bb6dbc52740d8c63fd6f3617

Also I've noticed just right now that we have Betamax cassettes for config tests (`tests/integration_tests/config/test_config.py`) even though these don't perform any HTTP requests. I would remove them. :)

**Comment by MarekSuchanek** [comment]
OK, should I use the changes from https://github.com/ds-wizard/dsw-sdk/commit/dc6b397077902408bb6dbc52740d8c63fd6f3617 directly or shall we merge it to this branch?

**Comment by drahoja9** [comment]
I’ll leave it up to you. :)

**Comment by MarekSuchanek** [comment]
@drahoja9 Any experience with the issue related to *coverage* plugin of pytest (only tests on Windows fail)? Or it may be probably caused by some dependency update...

**Comment by MarekSuchanek** [comment]
Fixed hopefully everything... the issue with coverage solved itself over time (probably some bug in some tests dependencies).

**Pull request merged**
